#!/bin/bash -e

export PATH=${SNAP}/bin:$PATH

# Prevents confined execution from failing due to inaccessible SSH agent socket.
unset SSH_AUTH_SOCK

# Default to KVM driver
extra=""
if [[ "$*" =~ start && ! "$*" =~ --vm-driver ]]; then
	extra="--vm-driver=kvm2"
fi

exec ${SNAP}/bin/minikube $@ $extra
