name: minikube
version: 0.27.0
summary: Run Kubernetes locally
description: |
    Minikube is a tool that makes it easy to run Kubernetes locally. Minikube
    runs a single-node Kubernetes cluster inside a VM on your laptop for users
    looking to try out Kubernetes or develop with it day-to-day.

confinement: strict
grade: stable

apps:
    minikube:
        command: minikube-wrapper
        plugs:
            - network
            - network-bind
            - libvirt

    ctl:
        command: bin/kubectl
        plugs:
            - network
            - network-bind

parts:
    go:
        source-depth: 1
        source-tag: go1.9.5

    kubectl:
        after: [go]
        plugin: make
        source: https://github.com/kubernetes/kubernetes.git
        source-depth: 1
        source-tag: v1.10.3
        artifacts:
          - _output/local/go/bin/kubectl
        make-parameters: [kubectl]
        install: |
          mkdir $SNAPCRAFT_PART_INSTALL/bin
          mv $SNAPCRAFT_PART_INSTALL/_output/local/go/bin/kubectl $SNAPCRAFT_PART_INSTALL/bin
        prime:
            - bin/*

    minikube:
        after: [go]
        plugin: go
        source: https://github.com/kubernetes/minikube.git
        source-depth: 1
        source-tag: v0.27.0
        go-importpath: k8s.io/minikube
        build-packages:
          - libvirt-dev
        build: |
          # "-e" causes realpath to fail if the directory does not exist, so
          # so we'll exit here if the plugin changes how it manages sources
          export GOPATH=$(realpath -e ../go)
          cd $GOPATH/src/k8s.io/minikube
          # disable chown in drivers.MakeDiskImage; it's a nop
          # when unconfined, but yields SIGSYS when confined
          echo H4sIAAxexFoAA41Sy27bMBA8W1+x1cmq9YyTNGgRIGgNtGnTIrDRc0BRS3lhShRIKo8W+feSkt04BgzkQJC7XM7sDLciISBJarLAsm5TZ5Wme9Rmt6e1gvLIRUBthY9wxvicz8uLIk3zvEQhiqqAIs/PT0+DJEmO4gaz2ew49tUVJMWHuMhh5rYLcLGkhiyzpFoDvaPWYNcIN8SxNZgG0DG+YTXCFiWAAKjplLYwDZJJSCoj1VuSYQCTUJlh65hdZ4Ik+kPoy8yT4Uz6In/vjFn3ZcpVk3Gp+kpIpjHjwhiZSVWHBzWV4hvUWcP4mlrMJJW747apcBSWn8UnhVOWz+NzL030LYefbIMLMpvrxqmYVvB+Z8dnZnAxnGMolbInI83v5Q0Yq6mtY6jcuxX9QaDWRoCurQkJQK3h4yVwjczikj28oHd9KYmvVt9+4NOtkz6tohHEBy9w0acB490ltCThr4edaLS9bn3eh8/Osz0qQY+3qBsyxn/TtEqXaJS8x5VVGgeiMA2jQ9jkNWwywvq1zbqyIHFxkAxOHbD4v9s6EXkApQdMZdIva/XQDvcxbD82/eogqZpGrzJY+1TkXvlhMDHceTXjvDgNrFqQHnCGEkdwF4PwJZq1buSGR6MQ0Y0+jCOVfle0a0Ckv1iDI8ueZf/bFN3bmnyDeTCsPfPgOfgHJftK5usDAAA= | base64 -d | zcat | patch -p1
          make
          make out/docker-machine-driver-kvm2
        install: |
          # "-e" causes realpath to fail if the directory does not exist, so
          # so we'll exit here if the plugin changes how it manages sources
          export GOPATH=$(realpath -e ../go)
          cd $GOPATH/src/k8s.io/minikube
          mkdir $SNAPCRAFT_PART_INSTALL/bin
          cp -a out/minikube out/docker-machine-driver-kvm2 $SNAPCRAFT_PART_INSTALL/bin
        prime:
            - bin/*

    ssh:
        after: [minikube]
        plugin: nil
        stage-packages:
            - openssh-client
        prime:
            - etc/ssh/*
            - usr/bin/*
            - usr/lib/*
            - usr/share/*

    copystuff:
        after: [minikube]
        plugin: dump
        source: .
        prime:
            - minikube-wrapper
            - bin/*
            - lib/*
            - lib64/*
            - usr/lib/*
            - usr/share/*
        stage-packages:
          # not sure who this is for, but snapcraft warned about it
          - libdb5.3
          # docker-machine-driver-kvm2's 16.04 dependencies
          - libapparmor1
          - libasn1-8-heimdal
          - libaudit1
          - libavahi-client3
          - libavahi-common3
          - libcap-ng0
          - libcomerr2
          - libcurl3-gnutls
          - libdbus-1-3
          - libdevmapper1.02.1
          - libffi6
          - libgcc1
          - libgcrypt20
          - libgmp10
          - libgnutls30
          - libgpg-error0
          - libgssapi3-heimdal
          - libgssapi-krb5-2
          - libhcrypto4-heimdal
          - libheimbase1-heimdal
          - libheimntlm0-heimdal
          - libhogweed4
          - libhx509-5-heimdal
          - libicu55
          - libidn11
          - libk5crypto3
          - libkeyutils1
          - libkrb5-26-heimdal
          - libkrb5-3
          - libkrb5support0
          - libldap-2.4-2
          - liblzma5
          - libnettle6
          - libnl-3-200
          - libnuma1
          - libp11-kit0
          - libpcre3
          - libroken18-heimdal
          - librtmp1
          - libsasl2-2
          - libselinux1
          - libsqlite3-0
          - libstdc++6
          - libsystemd0
          - libtasn1-6
          - libudev1
          - libuuid1
          - libvirt0
          - libwind0-heimdal
          - libxen-4.6
          - libxenstore3.0
          - libxml2
          - libyajl2
          - zlib1g
