name: minikube
version: 0.25.0
summary: Run Kubernetes locally
description: |
    Minikube is a tool that makes it easy to run Kubernetes locally. Minikube
    runs a single-node Kubernetes cluster inside a VM on your laptop for users
    looking to try out Kubernetes or develop with it day-to-day.

confinement: strict

apps:
    minikube:
        command: minikube-wrapper
        plugs:
            - home
            - network
            - network-bind
            - libvirt

    ctl:
        command: bin/kubectl
        plugs:
            - network
            - network-bind

parts:
    ssh:
        plugin: nil
        stage-packages:
            - openssh-client
        snap:
            - etc/ssh/*
            - usr/bin/*
            - usr/lib/*
            - usr/share/*

    copystuff:
        plugin: dump
        source: .
        snap:
            - minikube-wrapper
            - bin/*
