name: minikube
version: 0.25.0
summary: Run Kubernetes locally
description: |
    Minikube is a tool that makes it easy to run Kubernetes locally. Minikube
    runs a single-node Kubernetes cluster inside a VM on your laptop for users
    looking to try out Kubernetes or develop with it day-to-day.

confinement: strict

apps:
    minikube:
        command: minikube-wrapper
        plugs:
            - home
            - network
            - network-bind
            - libvirt

    ctl:
        command: bin/kubectl
        plugs:
            - network
            - network-bind

parts:
    ssh:
        plugin: nil
        stage-packages:
            - openssh-client
        snap:
            - etc/ssh/*
            - usr/bin/*
            - usr/lib/*
            - usr/share/*

    copystuff:
        plugin: dump
        source: .
        snap:
            - minikube-wrapper
            - bin/*
            - lib/*
            - lib64/*
            - usr/lib/*
            - usr/share/*
        stage-packages:
          # docker-machine-driver-kvm2's 16.04 dependencies
          - libapparmor1
          - libasn1-8-heimdal
          - libaudit1
          - libavahi-client3
          - libavahi-common3
          - libcap-ng0
          - libcomerr2
          - libcurl3-gnutls
          - libdbus-1-3
          - libdevmapper1.02.1
          - libffi6
          - libgcc1
          - libgcrypt20
          - libgmp10
          - libgnutls30
          - libgpg-error0
          - libgssapi3-heimdal
          - libgssapi-krb5-2
          - libhcrypto4-heimdal
          - libheimbase1-heimdal
          - libheimntlm0-heimdal
          - libhogweed4
          - libhx509-5-heimdal
          - libicu55
          - libidn11
          - libk5crypto3
          - libkeyutils1
          - libkrb5-26-heimdal
          - libkrb5-3
          - libkrb5support0
          - libldap-2.4-2
          - liblzma5
          - libnettle6
          - libnl-3-200
          - libnuma1
          - libp11-kit0
          - libpcre3
          - libroken18-heimdal
          - librtmp1
          - libsasl2-2
          - libselinux1
          - libsqlite3-0
          - libstdc++6
          - libsystemd0
          - libtasn1-6
          - libudev1
          - libuuid1
          - libvirt0
          - libwind0-heimdal
          - libxen-4.6
          - libxenstore3.0
          - libxml2
          - libyajl2
          - zlib1g
